language: java

jdk: openjdk8

addons:
  sonarcloud:
    organization: "ccathala"
    token:
      secure: "o/j3WMvviYQFqcsaLBfCeNJsJeGR+HaD+MZwu/VjzfVnaojRvzxoUutLxdchk062MiL6t71pqncSHYryfkCnYorFJHpXp2rU9UyKDGBabdWA0B9VIT1CZ3dmXi3MwBE6G5gsaTFJEPIGacFEyOE+wlUVAe36/pMWjSpiF+9ABWO4sqWbkUSr+KouSenIMsvs5VlapBL1HAg6jhmoL6Qaum8M+am5Nk/jKvq0T7A760OQQR9uY6kyBHpuII4JEVCn7aFJkuRIa2jgfZS959n5p3F+QkjZbQNKsSbM2jx4KYt6HHhXeVBp+TrhOn74X41kGssNtiSej/8D9CCrByHZGVzRKQh525n/sjfQ1fZZrxDiPVEozWgBB+esgU7afyV9Vw51ENog5XOgG+cVg0Do5GLcApObAjc491Bc1HtdyJIfPSA9A8Zl4Y/YSBKARzqCdGVUw5u94I0UnClv2Xif2ZqZzg7rPIbtXjlCsXwSuksffw3h/3gY0dJvyKI4mfRFsj2cvlBazdtfAzqHE8nJJs1ufl96l+OQcOqu5AqFa5AAZKpFQlo3TAtvW7mIrMRBMKT5Kz9HipGvnxzcp+tvU6a1Jkzzmf4IUD51+DZmm5EsfAdDG0rLEPj4Ht5AXRfqd5GHudkI61Cz0ZXIZdhwqVlW71G1p01pDiHBN3K0hHI="
sudo: required

before_install:
  - docker-compose up -d
  - docker ps -a

script:
  - cd api
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Ptest-integration -Dsonar.projectKey=ccathala_OC_Bibliotheque_P10
  - cd ..
  - docker-compose stop
  - docker-compose rm -f
  - docker-compose up -d
  - docker ps -a
